[build]
publish = "public"
command = "composer install && php artisan migrate && php artisan config:cache"

[context.production.environment]
PHP_VERSION = "8.2"

[[plugins]]
package = "@netlify/plugin-php"
