[context.production.environment]
PHP_VERSION = "8.2"

[build]
publish = "public/build"
command = "composer install && php artisan migrate && php artisan config:cache && npm run build"

[[redirects]]
from = "/*"
to = "/index.php"
status = 200
